source 'https://rubygems.org'
ruby '1.9.3'
gem 'json'
gem 'data_mapper'
gem 'hiredis'
gem 'dm-redis-adapter'
gem 'em-hiredis'
gem 'sinatra'
gem 'eventmachine'
gem 'sinatra-websocket'
gem 'diff_match_patch_native'
gem 'sinatra-authentication'
gem 'haml'
gem 'base62'
gem 'rainbows'
group :development do
	gem 'racksh'
	gem 'pry-rescue'
	gem 'pry-stack_explorer'
end
