source 'https://rubygems.org'
ruby '1.9.3'
gem 'json'
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'erubis'
gem 'redis'
gem 'hiredis'
#gem 'dm-redis-adapter'
gem 'em-hiredis'
gem 'sinatra', :require=>'sinatra/base'
gem 'eventmachine'
gem 'sinatra-websocket'
gem 'diff_match_patch_native'
gem 'sinatra-authentication'
gem 'haml'
gem 'base62'
gem 'thin'
gem 'sprockets'
gem 'sprockets-helpers', :require=>'sinatra/sprockets-helpers'
group :development do
	gem 'racksh'
	gem 'pry-rescue'
	gem 'pry-stack_explorer'
end
group :production do
    gem 'yui-compressor'
end
